### PR TITLE
Sublime linters

### PR DESCRIPTION
**Pull request by anniedaniel**
Made the code linter guide slightly more beginner-friendly.

fixing the internet

### CODE REVIEW

**Comment by crccheck** [comment]
you should look into eslint instead of jshint. It works a lot better with es6 and jsx. If you ever plan on doing d3, es6 syntax makes things a lot easier. Your d3 looks more like `.attr('width', (d) => xScale(d))` instead of `.attr('width', function (d) { return xScale(d); })`. And when you're doing d3, that makes literally half the lines easier. The es6 templating and multi-line strings are super-nice too.

**Comment by anniedaniel** [comment]
Uh oh, looks like atom-lint doesn't work with this newest version of atom :disappointed:

**Comment by rdmurphy** [comment]
That plugin is no longer used – they've moved on to [linter](https://atom.io/packages/linter), which works similarly to SublimeLinter. Also, this is a pull request for Sublime Text. Let's move discussion of Atom to its own issue. :)

**Comment by anniedaniel** [comment]
Oh I just named it Sublime because I forgot about Atom. But should I make a new guide for Atom?

**Comment by rdmurphy** [comment]
I think it's fine (and preferable!) to do them in to separate swings. Two discrete tasks!

**Comment by crccheck** [comment]
Two **atomic** tasks

**Comment by rdmurphy** [comment]
GAH.

**Comment by anniedaniel** [comment]
:100:

**Comment by rdmurphy** [comment]
Made my edits.

I pulled out the [Python rulers section](https://gist.github.com/rdmurphy/b4221b1a5f0bc63a8128). I think it'd make more sense living with the Sublime Text 3 setup section via the computer setup guide. It's a little out of place with the linters.

**Pull request merged**
